### ISSUE TITLE
Unable to display 3D normally

### ISSUE THREAD

**Issue by Chen2022** [adizanni/floor3d-card#101]
Help to see what the problem is, thank you!
sweet home 3D V6.6a
floor3d-card V1.4.1hf2

<img width="729" alt="6" src="https://user-images.githubusercontent.com/70124937/165219570-19ac026d-fc39-412a-b0cf-590a78674afe.png">

<img width="999" alt="1" src="https://user-images.githubusercontent.com/70124937/165218405-e617c9c6-6f99-42bf-bb50-b384546e8772.png">
<img width="781" alt="2" src="https://user-images.githubusercontent.com/70124937/165218413-5aa3dd38-bce1-4280-8c14-1fa5925d5630.png">
<img width="859" alt="3" src="https://user-images.githubusercontent.com/70124937/165218420-8e37e061-247d-4d90-9a8b-2a0fa87279a1.png">

But the default display is normal

<img width="949" alt="5" src="https://user-images.githubusercontent.com/70124937/165218967-8d12e71f-29ec-4318-a72c-26a49769ca8b.png">

**Comment by adizanni** [comment]
@Chen2022, since I put the sample in the release, I realized that people get more confused. 
First, you are not obliged to put your model into the HACS folder (..../community/....). Even if it works it is better to not touch the HACS folder and put your model (all files: obj, mtl, jpeg, etc) in  a dedicated folder (ex. /config/www/myhome/ for a Path in the card configuration that will be /local/myhome)
Second, remove the entities and the object groups from the sample. THey refer to objects of the sample model and they will fail when you change the model, as the card will not find anymore those objects.
Hope it clarifies, I think I will have to improve on the sample and the explanation. I thought it would help, instead it is generating more issues.

**Comment by Chen2022** [comment]
OK, thank you

**Comment by adizanni** [comment]
Is it working now ?

**Comment by Chen2022** [comment]
Yes, thank you
