### ISSUE TITLE
type3d:text - always default values 

### ISSUE THREAD

**Issue by DSF1979** [adizanni/floor3d-card#13]
**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**
When setting type3d:text , font, bg,fg colors are ignored
I've debugged a little and in _updateTextCanvas  looks like entity.text is an array and data is on element 0,  so it always reverts to the default values

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
P.S. type3d:text works only on simple objects, with names made only out of numbers, otherwise the object becomes black and no text is displayed.
![Capture](https://user-images.githubusercontent.com/56270510/123104404-34db2900-d437-11eb-978c-a9bf82417401.JPG)

**Comment by adizanni** [comment]
Hello, I must admit that I tested only on plane objects but I cannot reproduce your problem:

  - entity: sensor.lumi_lumi_sens_c5d91002_temperature
    type3d: text
    text:
      font: verdana
      textbgcolor: '#ffffff'
      textfgcolor: '#0000ff'
    object_id: Picture_1303
  - entity: sensor.lumi_lumi_sens_f4881002_temperature
    type3d: text
    text:
      font: verdana
      textbgcolor: '#ffffff'
      textfgcolor: '#00ff00'
    object_id: Picture_1310

![example](https://user-images.githubusercontent.com/35622920/123140011-1c7b0680-d457-11eb-91db-9be6e25f6dd2.png)

I will play around with other object types ......

**Comment by DSF1979** [comment]
Hello and thanks for great work .
Try to pick door or window objects and they will become black with no text.

About  the default values here is some js debug.
![Capture](https://user-images.githubusercontent.com/56270510/123142280-8a283200-d459-11eb-8534-cc0c0d5899e3.JPG)
text array is filled  t.text.font is _undefined_ so it picks the default value monosomething. Same story for textbgcolor, textfgcolor
![Capture](https://user-images.githubusercontent.com/56270510/123143225-9eb8fa00-d45a-11eb-93cb-d62819eb153e.JPG)

This is the config 
 - entity: sensor.radiator_left_air_temperature
            type3d: text
            object_id: '464'
            text:
              - font: verdana
                textbgcolor: '#00ff00'
                textfgcolor: red

**Comment by adizanni** [comment]
I have not the same debugging framework (by the way it would be good to know how to set it up). If you go to the console to verify the text object, it is not an array:

![textobject](https://user-images.githubusercontent.com/35622920/123145372-0ff9ac80-d45d-11eb-834e-c8dc245bcc41.png)

So I am really not able to reproduce or confirm your diagnostic and it does not make sense as it is not a Yaml array (it has no dashes).

I tried with a door and the bgcolor worked for me but the text is not showing. This is because it only works on 3d objects that have only 2 dimensions. I think this is due to the fact that the html canvas object is put in the middle of the object and it does not appear for solid objects.

**Comment by adizanni** [comment]
Sorry now I've seen your config. You have to remove the dash before the font tag......

**Comment by DSF1979** [comment]
Thank you for your quick answer. It works. Please update the official docs , it's still with dash :
![Capture](https://user-images.githubusercontent.com/56270510/123151573-e2fcc800-d463-11eb-9c7f-4f1c2dc65063.JPG)

How can I change the font size ?

**Comment by adizanni** [comment]
Yes, I changed the description. 

It is not possible to change the size of the font because the "text" entity is designed to span all the available space in the object plane.

I really suggest you to add a picture object on top of the surface where you  want the text to appear and bind it to the text entity.
This way you can set the size and position at will

**Comment by DSF1979** [comment]
I saw that the text spans the entire object length, but you can add a relative modifier property , for exempla a percent   -10% , -20% , +5% from the calculated size. 
Something like this 
text:
   font: arial
   relativefontsize: -20
   textbgcolor: red
It will fix my jacuzzi temperature :)
![Capture](https://user-images.githubusercontent.com/56270510/123155729-c2833c80-d468-11eb-8419-70cc9f35d144.JPG)

Thanks again for your great work.

**Comment by adizanni** [comment]
Thanks, now I see :).  Maybe turn it into a feature request, it is not a bad idea
