### ISSUE TITLE
Can't get camera position by double click

### ISSUE THREAD

**Issue by barbuuu** [adizanni/floor3d-card#136]
Hello, I'm using latest HA core today, all updates on Home Assistant. I follow your video and I have only one issue: I can't get the message with camera position by double click on empty space.

Any ideea how to solve this or at least how to get the camera coordinates in order to lock the camera view?

Appreciate!
Dan

**Comment by barbuuu** [comment]
Also the box showing object ID is not appearing. All those things are making your card useless :(

Dan

**Comment by p8ulus** [comment]
same here too, box object ID is not visible

**Comment by adizanni** [comment]
Hello @barbuuu @p8ulus, since 1.5.0 the card has implemented a new feature (Selection Mode) and the doubleclick is not by default. You have to put in the code editor the followoing option: editModeNotifications: 'yes' in order to re-establish the behaviour of my videos. I've not had time to do a video fort all those changes

**Comment by p8ulus** [comment]
thanks for quick reply

**Comment by adizanni** [comment]
Can we consider the bug as fixed ?

**Comment by p8ulus** [comment]
Yes 👍Op 6 nov. 2022 19:07 schreef andyHA ***@***.***>:
Can we consider the bug as fixed ?

**Comment by barbuuu** [comment]
Thank you very much! is working perfectly!
