### ISSUE TITLE
Popup for object id and camera position not showing up

### ISSUE THREAD

**Issue by splasheye** [adizanni/floor3d-card#142]
Hi I installed this about 5 months or so ago. Got it working to a point, then left it alone. I have the latest version installed and I have started back up around it again. At the time i installed it I was able to double click on objects to get the object_id from the pop-up window. At this time no pop-up window comes up, for that or the camera position x y z coordinates. I have tried it on 2 different computers and no luck. I have 2022.10 HA ver installed. Any help would be great.

**Comment by adizanni** [comment]
Hello @splasheye , since v1.5.0 the card has implemented a new feature (Selection Mode) and the doubleclick is not by default. You have to put in the code editor the followoing option: editModeNotifications: 'yes' in order to re-establish the behaviour of my videos. I've not had time to do a video for all those changes. Apologies

**Comment by splasheye** [comment]
Hi, thank you very much that did the trick. Is this still the only way to get the object_id ?
No reason to apologies for that video.
