### ISSUE TITLE
Uncaught error from Chrome 119.0.0.0 on Windows 10 Error

### ISSUE THREAD

**Issue by Trzinka** [adizanni/floor3d-card#171]
Logger: frontend.js.latest.202312082
Source: components/system_log/__init__.py:300
First occurred: 16:17:57 (1 occurrences)
Last logged: 16:17:57

Uncaught error from Chrome 119.0.0.0 on Windows 10 Error /hacsfiles/floor3d-card/floor3d-card.js:2288:34538 Object.s [as onError] (/hacsfiles/floor3d-card/floor3d-card.js:2231:539918) XMLHttpRequest.<anonymous> (/hacsfiles/floor3d-card/floor3d-card.js:2231:436056)

**Comment by adizanni** [comment]
Hello @Trzinka, I must say that since I put the card template I received a lot of tickets in GitHub. When you create a card from the template and then you change the model (removing the reference to the template model), you need to remove all references to the template objects in the entity and the object groups.

**Comment by adizanni** [comment]
Closing as stale for 2 months
