### ISSUE TITLE
Lights transpasing rooms through walls

### ISSUE THREAD

**Issue by jgarmar** [adizanni/floor3d-card#64]
**Checklist:**

- [x] I updated to the latest version available
- [ X] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

I'm using Chrome latest version

**Description of problem:**

Hello, first of all congratulate you on your work, it's amazing, really. I have a small problem and it is that the lights go through the walls as you can see in the image, any solution? Thank you

![image](https://user-images.githubusercontent.com/6642578/143316203-acf41491-f429-4d0f-9902-cb10ce4c847c.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by adizanni** [comment]
Hello @jgarmar, if you do not want this to happen, you need to use the shadow card parameter. Just set it like:

```yaml
shadow: 'yes'
```
bear in mind that this feature is consuming a lot of PC resources and that when you activate the shadow you can only have in your scene less a number of lights than is less than the number of "Max Texture Image Units" you will find in this report https://webglreport.com/?v=2, Since v1.1.5 of the card I have introduced the possibility to remove the shadow at light entity level for the lights you do not want to cast the shadow like this:

```yaml
entity: <light entity>
    .....
    light:
         shadow: 'no'
```
