### ISSUE TITLE
Overlay function only works on first object in an object group

### ISSUE THREAD

**Issue by greyhound3** [adizanni/floor3d-card#75]
If the objects in the group are resorted (with the arrow up/down symbols), the overlay is only displayed if the first object in the list is pressed.
Tested using Firefox v96.0.1 or Google Chrome v97.0.4692.71 on MacOs v11.6 with floor3d-card v 1.1.13
If more information is needed, I will post it.
It is not critical for me, I just wanted to mention it.
<img width="276" alt="grafik" src="https://user-images.githubusercontent.com/10048796/149638650-41edf224-024b-49bf-9060-7c161e323e24.png">
<img width="380" alt="grafik" src="https://user-images.githubusercontent.com/10048796/149638665-de24ec5c-dc36-4ac7-b806-c4ccd04eb711.png">
<img width="271" alt="grafik" src="https://user-images.githubusercontent.com/10048796/149638706-64c8d99e-6a2b-471a-9fc9-4f19679a6147.png">

**Comment by adizanni** [comment]
Hello @greyhound3, it is true. I'm having some trouble to keep the consistency of the card configuration. The problem is that I have a many to many relationship between the objects and the entities and it is unmangeable in the code. What-if you assign the object_id to another entity. I will try to address your specific issue but I think I need to perform a deeper restructuring in order to limit the association between objects and entities.

**Comment by greyhound3** [comment]
Thank you for your answer. The problem is really not bothering me, I just thought that I stumbled upon something fishy, which - when handeled otherwise - would or could solve other problems.
I used your suggestion in fact some time ago to turn a lamp with more than one bulb in it, since HA complained about not being able to toggle a group (not implemented), but using singular entities for every bulb worked and everything is fine!

**Comment by adizanni** [comment]
You are right your use case is legitimate, the problem is when I add a new feature, I need to manage more and more cases. So I will see if I can fix this easily

**Comment by adizanni** [comment]
Hello @greyhound3, I have checked your card configuration and I must say that you have created something that I didn't even know it could work. For me all entities needs a type3d and you managed to create an entity without type3d.By design overlay should only show the value of the entity associated to a clicked object , but the entity need to be of some type (light, camera, gesture, etc.). Second what do you want to achieve ? You have created a group of objects that belongs to different rooms and you associate only one sensor entity (sensor.temperature), is it intentional ? Third, even with all these conditions, the overaly should show the value of sensor.temperature when you click on any of the objects of the group...... I'm not sure I'm  clear

**Comment by greyhound3** [comment]
> 
GPT-3?

**Comment by greyhound3** [comment]
Well, my intention was to get the outside temperature, clicking on a window. Should be the same for every windows.

**Comment by greyhound3** [comment]
I wanted the 3d model as interactive as possible and to show the outside temperature on clicking any window.

**Comment by adizanni** [comment]
Ok it is clear. I confirm the bug and I have a fix for next release

**Comment by adizanni** [comment]
v1.1.14 is released and it should fix this issue. Please verify

**Comment by greyhound3** [comment]
> v1.1.14 fixed it, you did it! Thank you!!

**Comment by greyhound3** [comment]
v1.1.14 fixed it, works perfectly!
You did it, thank you !!
