### ISSUE TITLE
Light Bleed on floor

### ISSUE THREAD

**Issue by Travis-Prall** [adizanni/floor3d-card#81]
**Checklist:**

- [X ] I updated to the latest version available
- [ X] I cleared the cache of my browser

**Release with the issue:**
1.1.16
**Last working release (if known):**
Never
**Browser and Operating System:**

Seen on Linux Windows Firefox and Chrome

**Description of problem:**

I'm seeing a lot of light bleed from all my lights on the ground. I know there are windows there ,but this happens in rooms with no windows. Is there a way to stop this or reduce this effect? I find it really looks unrealistic when light bleeds through the ground.

### Porch light is on the other side of the wall.
![image](https://user-images.githubusercontent.com/56953579/154547506-b17162b3-508c-43b8-9f59-9eb43943d904.png)

### Picture of light on side of wall.
![image](https://user-images.githubusercontent.com/56953579/154547851-b6d8d416-6b7e-491d-b8c4-1a0081f73193.png)

**Additional information:**

**Comment by adizanni** [comment]
Hello Travis, when you want lights to stop at wall limit (like in the real world), you need to put first shadow: yes at global parameter level and also a shadow: yes for each of the lights that need to cast shadow. The reason why I do not do it by default is that shadows are consuming a lot of GPU resources and it may be unearable for mobile devices.

**Comment by Travis-Prall** [comment]
I thought it said "By default wall, floors and objects with "door" in the name, receives and cast shadows" Turning on shadows does solve the problem ,but makes everything slow. I was wondering if there was a way to isolate the light to a room without going all out on shadows. I really don't need shadows on everything ,but it would be great if it could stay in the room.

**Comment by adizanni** [comment]
The shadow is primarily a property of the light (if the light stops or not at wall and floor boundaries). For a 3D scene to be realistic the shadows have to be realistic. In order to be realistic, the 3d renderer has to calculate dynamically all possible combination of lights hitting a surface. The 3d model does not know what is a room, what if a door open and the light need to get out ? If you do not do it dynamically then you go back to the Picture Element solution that is nice but it is not dynamic. I'm conscious that this is a bad limitation and I'm studying some workarounds (trying to make lights conscious of walls and floors, but this is pretty complicated to implement or it will imply even bigger performance penalties.

**Comment by adizanni** [comment]
Hello Travis, the issue is too old and I do not consider it as a issue but as a fundamental limitation of the three.js library. If you want the light to be stopped then you need to activate the shadow and put no more than the MAX_TEXTURE_UNIT_IMAGES lights in your scene

**Comment by gcorgnet** [comment]
Sorry to get back to this @adizanni  but wondering if you could provide some insights:

I am still getting unexpected light bleed when turning on shadows.

Shadows off:
![image](https://user-images.githubusercontent.com/4731735/157532728-ced034ed-b7ac-4861-9864-7f3e53cdc86f.png)

Shadows on:
![image](https://user-images.githubusercontent.com/4731735/157533877-a9ca83ce-f413-4483-ba17-1c8915a16972.png)

It looks like it's happening due to furniture and doors.
What could I do?
Thanks
