### ISSUE TITLE
EDITOR ERROR - V 1.3.9

### ISSUE THREAD

**Issue by VITCHEPF** [adizanni/floor3d-card#89]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
floor3d-card - V1.39 

**Last working release (if known):**

**Browser and Operating System:**
Edition: Windows 10 Pro
Version: 21H2

**Description of problem:**
After updating to the floor3d-card - V1.39 version, when we start writing in the Entity field, the card stops working and crashes.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

1) Before 

![ERRO0](https://user-images.githubusercontent.com/73760504/158275169-f942e559-80fc-4c0d-bf94-aef16743fc6c.jpg)

2) When we start to type, in the first word

![ERRO1](https://user-images.githubusercontent.com/73760504/158275225-6e799bf7-8296-461d-a416-b2a3ec6b8fbb.jpg)

**Comment by adizanni** [comment]
Solved with v1.3.10. Even if I wanted to better manage the error, the current behaviour is that you lose the preview window when you show an error in the config: this is not the expected behaviour because you always want to have access to the preview while you are editing an entity or any other attribute and only show the error if you explicitly save the config or refresh (top left button in the visual editor ). Please tell me if 1.3.10 is solving your reported bug or suggest a different behaviour.

**Comment by VITCHEPF** [comment]
In version 1.3.10 when you create a New Entity, the word "undefined" appears and I can't delete with backspaces, as the input does not accept an initial value as empty

![Screenshot_20220315-173128](https://user-images.githubusercontent.com/73760504/158469187-9d577e89-d827-4f74-8e49-47b3a44a7227.jpg)

**Comment by adizanni** [comment]
Hello, I'm really sorry. I'm preparing a hot fix

**Comment by adizanni** [comment]
The editor fix due to HA 2022.3 caused me a lot of troubles and I have no time to do thourough testing.

**Comment by VITCHEPF** [comment]
I suggest you consider changing the input to a component like the droodown list, which shows all available entities in my HA, preventing us from typing a wrong name.

See example below:

![Screenshot_20220315-160715](https://user-images.githubusercontent.com/73760504/158473616-1602d9f5-fbd9-4621-879a-b5c7256566e4.jpg)

**Comment by adizanni** [comment]
There is already one but it is activated only if you have less than 40 entities, otherwise the editor becomes too heavy when you have many entities. Please check if hot fix 1 is really fixing

**Comment by adizanni** [comment]
In later releases I will try to integrate the Entity Picker that gives the possibility to type part of the entity name and receive suggestion based on  a list, it is the best compromise between usability and performances.

**Comment by VITCHEPF** [comment]
Please see some comments below:


![ERRO4](https://user-images.githubusercontent.com/73760504/158513740-b6bff066-bb4c-4f01-8c00-d1b00c59f6e1.jpg)




![ERRO5](https://user-images.githubusercontent.com/73760504/158513757-567001a1-2c43-48f0-8a8a-910413f8148d.jpg)

**Comment by adizanni** [comment]
Have you upgraded to the hotfix (1.3.10-hf1) ? If you  have I'm not able to reproduce the last behaviour you describe.
I totally agree, the card need a better error catching mechanism but HA does not facilitate the task. In the preview card I can only either show the errors or the model; I've not found the way to show both. The model has to stay open to retrieve the object names on double click. I need to find a way to display the model in a different mode when the editor is opened. 
It is not an easy card to manage and many other custom cards are not even providing the editors for much simpler functionalities.
I was even thinking to create a separate application and interact with the HA API instead of being limited by the custom card restrictions (I can tell you that when the new version of HA disrupted the card I was about to abandon all efforts). For instance I could use this [3d viewer](https://3dviewer.net/) and communicate with HA only via APIs and WebSocket. I have many ideas but not a lot of time to dedicate and to make the editor usable it is a lot of effort and potentially a lot of testing

**Comment by VITCHEPF** [comment]
Please, see below my comments regarding to the version v1.3.10-hf1:


![ERRO 1](https://user-images.githubusercontent.com/73760504/158696384-54d45f31-54d1-4870-9299-8395fa29113e.jpg)


LOG ERROR MESSAGE

![erro1](https://user-images.githubusercontent.com/73760504/158695850-0aff1f58-e013-44af-9de2-1b34ec27ccc4.jpg)

**Comment by adizanni** [comment]
Yes because you did not put the object name. Just look higher in the console log, you should see a caught  error saying that there is no object for the entity. I have to investigate because I have tried to force the re-render of the model only when you click the refresh button on the top left of the editor. It surprises me that the model is refreshed when you select the type3d: that is not the intended behaviour.

**Comment by VITCHEPF** [comment]
Hi adizanni, I did some tests with Home Assistant 2022.3.5 and hotfix (1.3.10-hf1), and the 3D Card seems to be more stable. No errors have occurred so far. I'll be proving new settings and let you know if I have any doubts.

Glad you didn't give up, because the tool is a fantastic idea

Congrats!

**Comment by adizanni** [comment]
Hello @VITCHEPF thank a lot for your contribution, it is only through your way of testing in-depth that the card can grow. I put the 1.x release tag too early; the card is still an idea more than a finished product. It is impossible for me alone to turn it into a product: the effort needed to code, test, deploy and make tutorials is too much.
