### ISSUE TITLE
RENDERIZATION

### ISSUE THREAD

**Issue by VITCHEPF** [adizanni/floor3d-card#90]
Dotted lines appear on the 3D object, like a rendering error. 
Why does it happen?

Is it possible to solve this problem? 
![ERRO0](https://user-images.githubusercontent.com/73760504/158292733-0e74ee09-cf22-40d6-89a2-d5337b5e95b8.jpg)

![ERRO1](https://user-images.githubusercontent.com/73760504/158292744-654996d7-b2a1-4206-9348-da64b0f0ada7.jpg)

**Comment by VITCHEPF** [comment]
See below the code:

type: custom:floor3d-card
entities:
  - entity: ''
object_groups:
  - object_group: ''
name: CASA DA SERRA
path: /local/casa_serra_3d/
objfile: home.obj?ver=1
mtlfile: home.mtl?ver=1
style: 'width: 900px; height: 640px'
globalLightPower: '0.92'
backgroundColor: black

**Comment by adizanni** [comment]
Hello @VITCHEPF I do not think this is coming from the config. Instead I think that this is coming from the model itself (wall junctions or window inserts, etc.). It would be interesting to import those models in Paint3d (windows 10) or in another viewer (ex. https://3dviewer.net/) to see if there are similar patterns.

**Comment by adizanni** [comment]
Hello @VITCHEPF can you please give an update here ? @uspass and myself, we think that those patterns are due to the wall that are not properly connected. Can you please try to see if changing the model has any effect on the pattern ?

**Comment by VITCHEPF** [comment]
Hi @adizanni, I checked the model in 3dviewer and there are the same patterns present.
Do you know if there is any solution to reduce this patterns (in Sweethome3D or in Floor3DCard)?

**Comment by adizanni** [comment]
Hello @VITCHEPF, in Sweethome3d use the magnetism and grid in order to ensure that walls, windows and other objects are sticking together. Also in the 2d view zoom in the wall junction to see if there are gaps. This can reduce the effect but not eliminate it, any micro variation or wall movement can create the problem in the card 3d rendering.

![image](https://user-images.githubusercontent.com/35622920/159114701-1f5941f7-8141-4934-9f5d-418b01327fa5.png)
