### ISSUE TITLE
North setting does not work (syntax ?)

### ISSUE THREAD

**Issue by 8OND007** [adizanni/floor3d-card#91]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
all

**Last working release (if known):**
none

**Browser and Operating System:**
Firefox/Chrome/Edge Windows

**Description of problem:**
The "North" parameters does not seem to adjust anything. What is the correct syntax for this parameter ?
even if I enter the default value of :   {x: 0, z: 1}  it does not work (shading is gone then).
With empty parameter value, shading is there, but with wrong North position. 
I want to change this but I don't get any working North parameter values working.
Give some working examples please.

Further the editor is very slow and buggy.

"Sky" & "Shadow" & "show_axes" parameters are set to "yes"

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by adizanni** [comment]
Hello @8OND007, try to use the code editor and enter the north this way. I do not know why but the object format is not working correctly:

```yaml
north:
  x: 0
  z: 1
```

**Comment by adizanni** [comment]
Related to the editor have you seen the performances going down with the last version (v1.3.11) ? 
You have to wait for the editor to load the card in the beginning, this is why it is taking a little more time, but during the editing the performances are quite acceptable (in my config)....

**Comment by adizanni** [comment]
Thanks for feedback @8OND007, the secret is a good GPU (this is fundamental for 3d rendering). Unfortunately this is against the HA principles. All HA software (add-ins, custom integraions and cards) should be working on any HW. I was thinking to have the 3d render built as a separate UI communicating to HA via API; I do not want to be reponsible for performance issue of the HA plarform.
I need to find a way to edit the card with or without preview in order to make the editing flawless

**Comment by adizanni** [comment]
@8OND007 can you please close this issue if you consider that it is fixed. I have updated the readme
